### ISSUE TITLE
Would it be possible to support the http protocol?

### ISSUE THREAD

**Issue by nathany** [homburg/git-get#6]
```
❯ git get https://github.com/thechangelog/changelog.com
Cloning into '/Users/nathany/src/https/github.com/thechangelog/changelog.com'...
fatal: I don't handle protocol 'git@https'

❯ git get github.com/thechangelog/changelog.com        
fatal: repository 'github.com/thechangelog/changelog.com' does not exist
```

😦

**Comment by homburg** [comment]
It absolutely should be supported :-)

The inspiration for the tool is of course `go get` which by default uses `https` instead of `ssh`.

My thoughts on solutions/behavior:

### 1. ssh as default, detect scheme/protocol prefix for http/https

ie.
- `git get http://github.com/some/thing.git` -> detect `://` -> `git clone https://github.com/some/thing.git`
- `git get some/thing` ->  `git clone git@<default domain>:some/thing.git`

### 2. configurable

Add an environment variable for setting the default protocol as http, https or git

### 3. automatic fallback to `https` for rejected clone on ssh

**Comment by homburg** [comment]
I'm partial to the first solution, as it seems fairly simple/intuitive without any ambiguities. Any thoughts/preferences?
